### ISSUE TITLE
[LDAPCPSE] After adding a LDAPS connection as second option, going to global config page will error out

### ISSUE THREAD

**Issue by desmondkung** [Yvand/LDAPCP#203] opened 2024-04-05 07:59 UTC
Hi Yvand, after adding a LDAPS connection as a second option and saving it, going back to the global config page will error out with "Exception of type 'SystemArgumentException' was thrown. Parameter name: claimType.

I need help to see the current claimTypes via PowerShell and to edit them if necessary.
Based on old docs, I can add type using 'Assembly Name="Yvand.LDAPCPSE, Version=1.0.0.0, Culture=neutral, PublicKeyToken=80be731bc1a1a740" '

What about the second line? How do I adapt the following to fit LDAPCPSE?
$config = [ldapcp.LDAPCPConfig]::GetConfiguration("LDAPCPConfig")

**Comment by Yvand** [comment] 2024-04-05 09:15
@desmondkung this is clearly unexpected. You can add an LDAPS entry using this PowerShell script:

```powershell
Add-Type -AssemblyName "Yvand.LDAPCPSE, Version=1.0.0.0, Culture=neutral, PublicKeyToken=80be731bc1a1a740"
$config = [Yvand.LdapClaimsProvider.LDAPCPSE]::GetConfiguration()
$settings = $config.Settings

# Add a new lDAP Connection
$ldapConnection = New-Object "Yvand.LdapClaimsProvider.Configuration.LdapConnection"
$ldapConnection.LdapPath = "LDAP://contoso.local:636/DC=contoso,DC=local"
$ldapConnection.Username = "<account>"
$ldapConnection.Password = "<password>"
$ldapConnection.EnableAugmentation = $true
$settings.LdapConnections.Add($ldapConnection)
$config.ApplySettings($settings, $true)
```

To understand your scenario, can you send the output of this:

```powershell
$trust = Get-SPTrustedIdentityTokenIssuer "YOUR_SPTRUST_NAME"
$trust.ClaimTypeInformation | fl MappedClaimType, IsIdentityClaim
```

**Comment by desmondkung** [comment] 2024-04-05 09:35
Restricted

Hi Yvand,

MappedClaimType: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn
IsIdentityClaim: True



Restricted

**Comment by desmondkung** [comment] 2024-04-05 09:50
Hi @Yvand,

MappedClaimType: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn
IsIdentityClaim: True

**Comment by desmondkung** [comment] 2024-04-05 09:52
Is there a way to reset all LDAPCPSE settings back to default via PowerShell so that I can try again? Including the removal of the recently added LDAPS connection.

**Comment by desmondkung** [comment] 2024-04-05 10:11
current ldap settings



Identifier                           : fe5fe0de-8c6a-48f6-8fff-d28e704771b6
LdapPath                             : Connect to SharePoint domain
Username                             : 
Password                             : 
AdditionalMetadata                   : 
AuthenticationType                   : Secure, Signing, Sealing
UseDefaultADConnection               : True
EnableAugmentation                   : False
GetGroupMembershipUsingDotNetHelpers : False
GroupMembershipLdapAttributes        : {memberOf, uniquememberof}
LdapEntry                            : System.DirectoryServices.DirectoryEntry
LdapEntryServerAndPort               : LDAP://<removed>
InitializationSuccessful             : False
DomainName                           : 
DomainFQDN                           : 
DomaindistinguishedName              : 
UpgradedPersistedProperties          : {}

Identifier                           : 9b9ec788-ad57-44e8-841d-5dabc8107cac
LdapPath                             : LDAP://<removed>
Username                             : <domain\username removed>
Password                             : <removed>
AdditionalMetadata                   : 
AuthenticationType                   : Secure, Signing, Sealing
UseDefaultADConnection               : False
EnableAugmentation                   : False
GetGroupMembershipUsingDotNetHelpers : False
GroupMembershipLdapAttributes        : {memberOf, uniquememberof}
LdapEntry                            : System.DirectoryServices.DirectoryEntry
LdapEntryServerAndPort               : LDAP://<removed>
InitializationSuccessful             : False
DomainName                           : 
DomainFQDN                           : 
DomaindistinguishedName              : 
UpgradedPersistedProperties          : {}

**Comment by Yvand** [comment] 2024-04-05 10:41
> Is there a way to reset all LDAPCPSE settings back to default via PowerShell so that I can try again? Including the removal of the recently added LDAPS connection.

You can run those commands to delete and recreate the configuration:

```powershell
[Yvand.LdapClaimsProvider.LDAPCPSE]::DeleteConfiguration()
[Yvand.LdapClaimsProvider.LDAPCPSE]::CreateConfiguration()
```

**Comment by desmondkung** [comment] 2024-04-05 11:15
1) I've deleted and re-created the configuration via PowerShell by running those two commands.
2) In central admin, I deleted the default LDAP connection to SharePoint domain and added only the LDAP server I want to connect to.
3) Clicked on the "Test LDAP Connection" and it passed.
4) Clicked on "Add LDAP Connection", then click on "OK" at the top.
5) Back at the Security page, click on "Global configuration" and error appears.

**Comment by desmondkung** [comment] 2024-04-05 11:19
Another way to reproduce.

1) Delete and re-create the configuration via PowerShell.
2) In central admin, go to security, click on global configuration.
3) Click on "OK" button at the top.
4) Back at the Security page, click on "Global configuration" and error appears.

**Comment by desmondkung** [comment] 2024-04-06 04:53
There's only 1 line if I filter ULS logs via Product.

"Successfully updated configuration 'LDAPCPSEConfig' with Id <guid>"

Is there an email I can send the ULS log to? About 275 KB.

**Comment by Yvand** [comment] 2024-04-08 14:13
@desmondkung the log is not giving more information. I would really like to understand the root cause: Are you able to repro the issue, whatever you type in the new LDAP connection? Can you repro if you remove the default LDAP connection?

**Comment by desmondkung** [comment] 2024-04-08 14:22
> @desmondkung the log is not giving more information. I would really like to understand the root cause: Are you able to repro the issue, whatever you type in the new LDAP connection? Can you repro if you remove the default LDAP connection?

I can try tomorrow morning.
To make sure I understand correctly, are you asking if I remove the default LDAP connection, leaving it with no LDAP connection, will the issue occur?

**Comment by desmondkung** [comment] 2024-04-09 05:27
Sent you 3 problem step recorder files for the following scenarios. All of them have identical error.
1) With default LDAP
2) With no LDAP
3) With default LDAP and random LDAP

**Comment by Yvand** [comment] 2024-04-11 12:12
@desmondkung the error happens because there is no group claim type set in the trust in your environment.
I opened PR https://github.com/Yvand/LDAPCP/pull/207 to handle this correctly.

In the meantime, you can fix the issue in the current version by removing the group claim type from the LDAPCPSE configuration, using the script below:

```
Add-Type -AssemblyName "Yvand.LDAPCPSE, Version=1.0.0.0, Culture=neutral, PublicKeyToken=80be731bc1a1a740"
$config = [Yvand.LdapClaimsProvider.LDAPCPSE]::GetConfiguration()
$settings = $config.Settings
$settings.ClaimTypes.Remove($settings.ClaimTypes.GroupIdentifierConfig)
$config.ApplySettings($settings, $true)
```powershell

**Comment by desmondkung** [comment] 2024-04-12 01:49
Error: Value cannot be null. Parameter name: type.

**Comment by Yvand** [comment] 2024-04-12 14:43
weird that I did not repro it, but it should be fixed in https://github.com/Yvand/LDAPCP/commit/b4c5d9703f94fb279dd608f1c34a03365ba4c24f

**Comment by desmondkung** [comment] 2024-04-14 03:54
I think the only way left to tell would be to deploy the new release once your pull request is done.

**Comment by Yvand** [comment] 2024-04-15 08:26
I just published a nightly build which contains this fix

**Comment by desmondkung** [comment] 2024-04-15 09:54
Just tested. No more error messages =)

**Comment by Yvand** [comment] 2024-04-15 11:32
Thanks for confirming!

**Closed** 2024-05-13 12:12 UTC
Labels: bug, Issue
