### ISSUE TITLE
domain prefix does not appear for local domain

### ISSUE THREAD

**Issue by SaboorQuadri** [Yvand/LDAPCP#89] opened 2019-07-24 09:33 UTC
I have configured SharePoint to authenticate via ADFS. So, I have 2 domains, Local and external.

Local domain ADSF is connected with External domain ADFS to authenticate user and LDAP port is enable between my SP server and external domain LDAP server.

Now, i have configured claim type for sAMAccountName with claim type as http://schemas.xmlsoap.org/claims/Group and claim value prefix as "{domain}\".

Problem is, while looking up ADgroup of external domain, it return a value with "**(AttributeDispalyName) Domain\ADGroupName**"
but while looking up local domain ADGroup, it returns a value without domain
"**(AttributeDispalyName) \ADGroupName**"

Unexpected Error in ULS logs:
Category: Claim Picking
EventID: 1337
Message:[LDAPCP] Validation failed: found 0 entities instead of 1 for incoming claim with value '\ADGroupName' and type 'http://schemas.xmlsoap.org/claims/Group'

LDAPCP version:
LDAPCP 13.0.20190621.905

**Comment by SaboorQuadri** [comment] 2019-07-24 10:13
Hi Yvad,

Just to add an update, It seems this is a problem only with below option

New LDAP connection : Connect to SharePoint AD domain

As a work around, i tried adding local domain LDAP using  a second option i.e. "Connect to a LDAP server" using Central admin app pool account credentials and tried to lookup local domain AD group in people picker. The result is as expected.

(AttributeDispalyName) Domain\ADGroupName

Please see if you check if there is any Bug in that option.

**Comment by Yvand** [comment] 2019-07-25 08:49
@SaboorQuadri thank you for reporting the issue
As it is a duplicate of https://github.com/Yvand/LDAPCP/issues/87 I'm closing this one.
If you believe your scenario is different feel free to reopen it

I'm troubleshooting it and will add more information soon

**Comment by SaboorQuadri** [comment] 2019-07-26 11:24
@Yvand , I have seen that case before raising this case. I see the end goal is same however, scenario and ULS error messages are different. It happens many time that same issue occurs with different cause. So, I believe, you can keep this case separate than #87 .

Also, please consider the work around which solved my problem however, I still believe you can go deeper in this area to identify why it is not working with default configurations for local domain.

**Comment by Yvand** [comment] 2019-08-06 16:33
@SaboorQuadri today I published pre-release https://github.com/Yvand/LDAPCP/releases/tag/14.0.20190806.943 that may fix the issue.
Are you willing to test it?

**Comment by SaboorQuadri** [comment] 2019-08-07 07:51
@Yvand , Sure, I can try and give you update. Also, i would like to know why the application association is removed in LDAPCP and if there is an alternate option provided for that. As in the older version we have an option to associate the web application with LDAP connection which isolates the requirement in same environment.

**Comment by SaboorQuadri** [comment] 2019-08-07 08:56
@Yvand , I tested upgrading the LDAPCP wsp with 14.0.20190806.943 version and it works very well for local domain Security groups. I removed the local LDAP path and tried to add new LDAPCP commention using "Connect to SharePoint AD domain" option. It work well now. Please let me know how can i bind a particular LDAP connection to specific webapplication while the option is removed from the latest LDAPCP versions.

**Comment by Yvand** [comment] 2019-08-07 11:21
@SaboorQuadri thank you for the test and the confirmation.

About the option you are describing, I don't remember it has ever existed in LDAPCP.
What version allowed you to configure that?
How did it manifest in the admin pages?

**Comment by SaboorQuadri** [comment] 2019-08-07 14:29
@Yvand , I do not know the version it have, however, i am attaching the screenshot and a wsp for your reference.

![image](https://user-images.githubusercontent.com/53221436/62630808-443d5000-b94d-11e9-903f-7b25a28a02c9.png)

[ldapcp.zip](https://github.com/Yvand/LDAPCP/files/3477471/ldapcp.zip)

**Comment by Yvand** [comment] 2019-08-20 08:34
@SaboorQuadri this option was never part of the standard LDAPCP, this is a customization done on your side. But I like the idea and I may implement it in a future version

**Comment by SaboorQuadri** [comment] 2019-08-22 06:50
@Yvand , May be it have been done long back by someone in my team before I join. Thank you for your support. It was an awesome conversation. Please do let me know when you implement this in LDAPCP so that we can use it.

**Comment by Yvand** [comment] 2019-08-22 16:01
Sure np!

**Closed** 2019-11-07 14:31 UTC
Labels: bug
