### ISSUE TITLE
Not able to add new member to Site Collection Administrator 

### ISSUE THREAD

**Issue by Faridmob** [Yvand/LDAPCP#96] opened 2019-08-30 14:41 UTC
I used LDAPCP with SharePoint 2019 and everything is working as per my expectation other than when adding new member to site collection administrator (SCA) in site collection level and get "An unexpected error has occurred" it is only in SCA and there is issue neither in site permission nor adding admin user through central admin.
I used v2017.10 and latest version as v13.0.20190621.905, but both produce the same issue and also I am using the same configuration is done in SharePoint 2016 that works fine.
I tried to find something in ULS log and grabbed some unexpected level as following

Unexpected	[LDAPCP] Unexpected error occurred while connecting to LDAP server LDAP://...... System.DirectoryServices.DirectoryServicesCOMException: An operations error occurred.  , Callstack:

Unexpected	[LDAPCP] Validation failed: found 0 entities instead of 1 for incoming claim with value '' and type 'http://schemas.microsoft.com/ws/2008/06/identity/claims/role'

Unexpected	GetUserInfoFromMembershipProvider: Request is in a web context and we can't find the user so we are failing. LoginName: '', bIsRole: 'True'

Unexpected	ensureUserExistsInternal2: Could not get user so failing without assert. wzLogin: '', bUseVerifiedUserKey: 'True', bImportDeleted: 'False'

Unexpected	System.Runtime.InteropServices.COMException: The user does not exist or is not unique.    at Microsoft.SharePoint.Library.SPRequestInternalClass.UpdateMembers(String bstrUrl, UInt32 dwObjectType, String bstrObjId, Guid& pguidScopeId, Int32 lGroupID, Int32 lGroupOwnerId, Object& pvarArrayAdd, Object& pvarArrayAddIds, Object& pvarArrayLoginsRemove, Object& pvarArrayIdsRemove, Boolean bRemoveFromCurrentScopeOnly, Boolean bSendEmail)     at Microsoft.SharePoint.Library.SPRequest.UpdateMembers(String bstrUrl, UInt32 dwObjectType, String bstrObjId, Guid& pguidScopeId, Int32 lGroupID, Int32 lGroupOwnerId, Object& pvarArrayAdd, Object& pvarArrayAddIds, Object& pvarArrayLoginsRemove, Object& pvarArrayIdsRemove, Boolean bRemoveFromCurrentScopeOnly, Boolean bSendEmail)

Thanks, 
Farid

**Comment by Faridmob** [comment] 2019-09-13 14:26
Hi Yvand,
Yes it does and and it is the same error, however, I installed v14 but it didn't worked out and getting the same error. Also when trying add member into Term Store through Term Store management in a site collection it is not able to find the user while adding through central admin is ok

**Comment by Yvand** [comment] 2019-09-16 09:01
Can you copy the full details of the DirectoryServicesCOMException?

**Comment by Faridmob** [comment] 2019-09-16 15:10
For sure here is the detailed

Unexpected	 [LDAPCP] Unexpected error occurred while connecting to LDAP server LDAP://.................../DC=……,DC=…..,DC=….: System.DirectoryServices.DirectoryServicesCOMException: An operations error occurred.  , Callstack:    at System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)     at System.DirectoryServices.DirectoryEntry.Bind()     at System.DirectoryServices.DirectoryEntry.get_AdsObject()     at System.DirectoryServices.DirectorySearcher.FindAll(Boolean findMoreThanOne)     at ldapcp.LDAPCP.<>c__DisplayClass43_0.<QueryLDAPServers>b__1(LDAPConnection ldapConnection)	33ca049f-a204-304b-bc4c-e6b7acadfeca


Unexpected	System.Runtime.InteropServices.COMException: The user does not exist or is not unique.    at Microsoft.SharePoint.Library.SPRequestInternalClass.UpdateMembers(String bstrUrl, UInt32 dwObjectType, String bstrObjId, Guid& pguidScopeId, Int32 lGroupID, Int32 lGroupOwnerId, Object& pvarArrayAdd, Object& pvarArrayAddIds, Object& pvarArrayLoginsRemove, Object& pvarArrayIdsRemove, Boolean bRemoveFromCurrentScopeOnly, Boolean bSendEmail)     at Microsoft.SharePoint.Library.SPRequest.UpdateMembers(String bstrUrl, UInt32 dwObjectType, String bstrObjId, Guid& pguidScopeId, Int32 lGroupID, Int32 lGroupOwnerId, Object& pvarArrayAdd, Object& pvarArrayAddIds, Object& pvarArrayLoginsRemove, Object& pvarArrayIdsRemove, Boolean bRemoveFromCurrentScopeOnly, Boolean bSendEmail)	33ca049f-a204-304b-bc4c-e6b7acadfeca

**Comment by Yvand** [comment] 2019-09-17 15:29
There is only 1 place where LDAPCP uses DirectorySearcher.FindAll(), and all the details of the LDAP query are recorded in the logs. Can you get them from the logs? First you need to set LDAPCP to verbose:

```
"LDAPCP:*"| Set-SPLogLevel -TraceSeverity Verbose
```

**Comment by Faridmob** [comment] 2019-09-17 16:35
Just for clarification, is LDAP log is in the same SharePoint log location?

**Comment by Yvand** [comment] 2019-09-18 07:27
Yes, AzureCP writes into SharePoint logs

**Comment by Faridmob** [comment] 2019-09-18 13:18
LDAPCP                        	LDAP Lookup                   	1337	Verbose	[LDAPCP] Connecting to "LDAP://domian1.domian.ca/DC=domian1,DC=domian,DC=ca" with AuthenticationType "Secure, Signing, Sealing", authenticating as process identity and sending a query with filter "(&(!(userAccountControl:1.2.840.113556.1.4.803:=2))(| (&(objectclass=user)(sAMAccountName=user)(!(objectClass=computer))) ))"...	bd23059f-c282-304b-bc4c-e14441362c62

LDAPCP                        	LDAP Lookup                   	1337	Unexpected	[LDAPCP] Unexpected error occurred while connecting to LDAP server LDAP://domian1.domian.ca/DC=domian1,DC=domian,DC=ca: System.DirectoryServices.DirectoryServicesCOMException: An operations error occurred.  , Callstack:    at System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)     at System.DirectoryServices.DirectoryEntry.Bind()     at System.DirectoryServices.DirectoryEntry.get_AdsObject()     at System.DirectoryServices.DirectorySearcher.FindAll(Boolean findMoreThanOne)     at ldapcp.LDAPCP.<>c__DisplayClass43_0.<QueryLDAPServers>b__1(LDAPConnection ldapConnection)	bd23059f-c282-304b-bc4c-e14441362c62

LDAPCP                        	LDAP Lookup                   	1337	Verbose	[LDAPCP] Got 0 result(s) in 13ms from all servers with query "(&(!(userAccountControl:1.2.840.113556.1.4.803:=2))(| (&(objectclass=user)(sAMAccountName=user)(!(objectClass=computer))) ))"	bd23059f-c282-304b-bc4c-e14441362c62

LDAPCP                        	Claims Picking                	1337	Unexpected	[LDAPCP] Validation failed: found 0 entities instead of 1 for incoming claim with value 'user' and type 'http://schemas.xmlsoap.org/claims/CommonName'	bd23059f-c282-304b-bc4c-e14441362c62

**Comment by Yvand** [comment] 2019-09-19 08:02
These logs give you all the details you need to replay the LDAP query in PowerShell using [this script](https://ldapcp.com/Troubleshoot-LDAPCP.html).
You should be able to repro the error and troubleshoot it outside of SharePoint/LDAPCP.
I don't think there is anything wrong in LDAPCP code, but this test will make sure of this.

**Comment by Faridmob** [comment] 2019-09-19 16:01
Thanks! I replayed the LDAP query and everything was ok without any error.
Again here is the thing, it is happening only in SP 2019 and adding new member to SCA. all settings and configuration is similar in SP 2016 and it worked properly in 2016

**Comment by Yvand** [comment] 2019-09-25 09:19
Out of curiosity, did you run the script as the farm account? 
Also, does LDAPCP work in other pages of central admin? For example, does LDAPCP work in web application > user policy page?

**Comment by Faridmob** [comment] 2019-09-25 15:32
yes it was with farm account.
yes it works in all pages in CA like user policy , change site collection administrators or Term Store Administrators  in MMS.
But when trying to add new member in Term Store Administrators in site collection it can't find the user

**Comment by Yvand** [comment] 2019-09-27 08:18
It is a bit confusing because initially I understood you couldn't set site collection administrator, and now this seems to work and what doesn't work is to set Term Store Administrators.

Also, the logs shows a DirectoryServicesCOMException when sending the query to LDAP server. This is an exception you should be able to reproduce with the PowerShell script I sent you earlier. I understand you don't and, assuming you replayed it correctly, I don't know what can cause this.

Last suggestion: In LDAPCP Add / replace current connection, with the same but with no encryption of traffic (remove options "Secure, Signing, Sealing"). If you still reproduce the issue, you can capture a network trace that will show the LDAP traffic in clear text, and you can analyze it further.

**Comment by Faridmob** [comment] 2019-09-27 13:46
Sorry if I confused you..... I was saying besides SCA issue I am not able to find a user in Term Store Administrators in site collection while everything is ok thru central admin to add site collection admin and Term store also there is no issue for adding a new user in site permission.

About the suggestion, I would say that I haven't used these option at all(if I am correct they are in LDAPCP Configuration/Global configuration

**Comment by Yvand** [comment] 2019-10-01 14:28
@Faridmob I think the suggestion I made remains relevant: I assume you are using the default connection "Connect to SharePoint domain". That LDAP connection is always "Secure, Signing, Sealing", so if you capture a netork trace while you use it, you will see nothing. Btw, you can see by yourself from the logs you copied that the connection is "Secure, Signing, Sealing"

**Comment by Faridmob** [comment] 2019-10-04 13:22
Hi Yvand,
yes we are using default connection like 2013 and 2016.
I could with Microsoft Escalation Engineer help through network trace, monitor and fiddler find the issue and solution for that
•	The LDAPCP error kept complaining about not able to connect to AD when the issue occurs so we tested our ability to bind to the domain controllers via PowerShell and all returned success.
•	To resolve this issue unlike 2013 and 2016 we removed the default connection and created the same LDAP connection manually with "Secure, Signing, Sealing" and everything went well and worked

**Comment by Yvand** [comment] 2019-10-04 14:17
This is very good news! I'm closing this issue, feel free to re-open it if needed

**Closed by Yvand** 2019-10-04 14:17 UTC
Labels: bug

**Comment by GoudGanesh** [comment] 2020-01-04 16:51
Hi Farimob,

I am also exactly facing same issue after we migrated SharePoint 2013 to SharePoint 2019.
In SharePoint 2013 we used LDAPCP claim provider and it worked perfectly with default ladap connection. We are using ADFS SAML token authentication. 

Where as in SP2019 I tried with newer version LDAP 14.1... but I am getting error while adding users to any SharePoint group after adding LDAP claim provider.

I followed the above conclusion in this thread. But I am still facing this issue. 
Error logs 
"Add" with "4" argument(s): "The user does not exist or is not unique."  
01/03/2020 06:13:28.84 	PowerShell_ISE.exe (AZWEUTBXSPW2019:0x2C40)	0x1CB4	LDAPCP                        	Claims Picking                	1337	Unexpected	[LDAPCP] Validation failed: found 0 entities instead of 1 for incoming claim with value 'ramur9' and type 'http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsaccountname'

Could you explain do i missing any thing here?
Thanks,
Ganesh
